mycodec: driver.cpp refpng.cpp mycodec.cpp rle.cpp bucket.cpp color_transform.cpp compress.cpp
	g++ -std=c++11 -O3 -o mycodec driver.cpp \
				refpng.cpp mycodec.cpp rle.cpp bucket.cpp color_transform.cpp \
				compress.cpp \
				-lpng -lz
